### ISSUE TITLE
Question: TypeScript Typings

### ISSUE THREAD

**Issue by qruzz** [Swizec/useAuth#27]
I watched the part of the video on you open sourcing this and you mentioned relying on the community to supply typescript typings.

I would be more than happy to help out with this, although there are some different ways we could go about it:
- Do we re-write `react-use-auth` in typescript, or just provide the typings as separate `*.d.ts` files?
  - This is ultimately a @Swizec question as this is your library and you would need to buy in to this. I am personally for it since the library is still rather small and it would not take long to convert to typescript. I have also seen that you have used typescript on some other projects, so it seems that you are familiar with it. The library is also quite limited in scope, meaning it is unlikely to gain a ton of new features over time. The downside however is, it would require all contributors to understand typescript, so it has it's pro/cons.
  - Re-writing it in typescript would mean that the typings are always in sync, and we could get some inferred typings/etc.
  - We could also release a separate `@types/react-use-auth` npm package and keep the typings completely out of the `react-use-auth` repository (although these would likely get out of date regularly I'd imagine).
- Do we use `tsc` for the builds or `babel` and `@babel/plugin-transform-typescript`?
  - Using `babel` allows us to leverage other babel plugins like macros, etc (although none are currently used)
  - `babel` does not support all typescript features, but 98% of them

**Comment by williamluke4** [comment]
An example using [tsdx](https://github.com/palmerhq/tsdx#readme) 
https://github.com/atto-byte/useAuth
I can make a PR, if everyone is fine with switching to TSDX

**Comment by Swizec** [comment]
This looks amazing! I would love a PR so I can take a closer look.


Also I'm a little confused by the UX here. I see this in an email chain that started 1 month ago, but can't find the discussion on the github repo ... so I hope my reply gets to you and the PR shows up.


Been thinking of taking on the schlep to convert the whole library to TypeScript but haven't found the time. So this is really perfect :)

—
swizec@swizec.com

--- original message ---
On September 20, 2019, 9:23 AM PDT notifications@github.com wrote:


An example using tsdx

https://github.com/atto-byte/useAuth

I can make a PR, if everyone is fine with switching to TSDX

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by qruzz** [comment]
GitHub is wonderful sometimes !
Well, as I suggested in the issue when I opened @Swizec , there were a few different ways we could go about providing TypeScript types.

I would be willing to make a PR where the whole thing is converted to TypeScript if that is the way you want to go with it. I just didn't want to do that, if you'd rather have types in DefinitlyTyped

**Comment by williamluke4** [comment]
I think having It writing in typescript is a much better option, as it flagged some issue when I was doing the conversion. I will make a PR this weekend as I need to revert some additional changes that I made to the ReadMe and add the examples back in.

**Comment by williamluke4** [comment]
Hey guys, I'm pretty swamped at the moment. @qruzz Feel free to grab the types from my package and submit them to DefinitlyTyped if you want.

**Comment by qruzz** [comment]
I'll see if I can find some time tonight to take a look at it -

**Comment by Swizec** [comment]
Thanks for the push fellas, useAuth is now in TypeScript ✌️
